### ISSUE TITLE
Add placeholder in profile

### ISSUE THREAD

**Issue by kubil-ismail** [IrhamNfrnda/food-recipe-fe-react#3]
After register i saw many blank area, please add placeholder section for user experience
![Screenshot (115)](https://github.com/IrhamNfrnda/food-recipe-fe-react/assets/49361887/70894ba7-8aa8-4249-b010-da0d96205ab7)

**Comment by IrhamNfrnda** [comment]
Done,
![Opera Snapshot_2023-08-09_104114_food-recipe-fe-react-ochre vercel app](https://github.com/IrhamNfrnda/food-recipe-web/assets/55636345/6d1dd47b-2952-4df6-9e2f-cf3af32fb7e5)
