### ISSUE TITLE
Layout break in profile recipe

### ISSUE THREAD

**Issue by kubil-ismail** [IrhamNfrnda/food-recipe-fe-react#4]
![Screenshot (116)](https://github.com/IrhamNfrnda/food-recipe-fe-react/assets/49361887/724eccf9-e6ae-4ab0-aa42-38624d5f7cca)

**Comment by IrhamNfrnda** [comment]
Fixed
![Responsive Desktop](https://github.com/IrhamNfrnda/food-recipe-web/assets/55636345/ebf3b1ed-8a99-462c-be41-cce46623f329)

**Comment by kubil-ismail** [comment]
![Screenshot (165)](https://github.com/IrhamNfrnda/food-recipe-web/assets/49361887/8026d2e4-cb9a-4311-be9b-630a1108722b)

Not Done

**Comment by IrhamNfrnda** [comment]
Layout break fixed

![Opera Snapshot_2023-08-15_201319_food-recipe-fe-react-ochre vercel app](https://github.com/IrhamNfrnda/food-recipe-web/assets/55636345/b1f6f3b5-1e75-488a-a508-317c1f57c09e)

**Comment by kubil-ismail** [comment]
![Screenshot (176)](https://github.com/IrhamNfrnda/food-recipe-web/assets/49361887/39c3bc8c-9d1f-47b3-b075-3becf8fdffab)
