### ISSUE TITLE
Data not showing

### ISSUE THREAD

**Issue by kubil-ismail** [IrhamNfrnda/food-recipe-fe-react#6]
It's because base url using localhost
![Screenshot (121)](https://github.com/IrhamNfrnda/food-recipe-fe-react/assets/49361887/d8c1dfcf-be9c-4fe9-b84b-20ca31571faf)

**Comment by IrhamNfrnda** [comment]
Fixed
![Data Show](https://github.com/IrhamNfrnda/food-recipe-web/assets/55636345/d95d73d1-f0aa-4f47-bedb-888c438730cc)
