### ISSUE TITLE
Layout break in login

### ISSUE THREAD

**Issue by kubil-ismail** [IrhamNfrnda/food-recipe-fe-react#7]
<img width="1680" alt="Screenshot 2023-08-10 at 11 17 07" src="https://github.com/IrhamNfrnda/food-recipe-web/assets/49361887/60838b7c-1b8e-4f08-a39e-a886095d789a">

**Comment by IrhamNfrnda** [comment]
Fixed

![Opera Snapshot_2023-08-11_103313_localhost](https://github.com/IrhamNfrnda/food-recipe-web/assets/55636345/31cefec1-5f5c-414c-a4cf-9a0cf3aa5712)
